EgitimPortali/Models/Education.cs
using System.ComponentModel.DataAnnotations;

namespace EgitimPortali.Models
{
    public class Education : BaseEntity
    {

        public string Name { get; set; }

        public string Description { get; set; }


        public int? LessonId { get; set; }
        public Lesson Lesson { get; set; }




    }
}

EgitimPortali/Controllers/EducationController.cs
using AspNetCoreHero.ToastNotification.Abstractions;
using AutoMapper;
using EgitimPortali.Models;
using Microsoft.AspNetCore.Mvc;
using EgitimPortali.Repositories;
using EgitimPortali.ViewModels;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;


namespace EgitimPortali.Controllers
{
    public class EducationController : Controller
    {
        private readonly EducationRepository _educationRepository;
        private readonly LessonRepository _lessonRepository;
        private readonly IMapper _mapper;
        private readonly INotyfService _notyf;
        private readonly AppDbContext _context;
        public EducationController(EducationRepository educationRepository, LessonRepository lessonRepository, IMapper mapper, INotyfService notyf)
        {
            _educationRepository = educationRepository;
            _lessonRepository = lessonRepository;
            _mapper = mapper;
            _notyf = notyf;
        }
        public async Task<IActionResult> Index()
        {
            var educations = await _educationRepository.GetAllAsync();
            var educationModels = _mapper.Map<List<EducationModel>>(educations);
            return View(educationModels);
        }
        [Authorize(Roles = "Admin,Teacher")]
        public async Task<IActionResult> Add()
        {
            var lessons = await _lessonRepository.GetAllAsync();
            var lessonsSelectList = lessons.Select(x => new SelectListItem()
            {
                Text = x.Name,
                Value = x.Id.ToString()
            });
            ViewBag.Lessons = lessonsSelectList;
            return View();
        }
        [HttpPost]
        public async Task<IActionResult> Add(EducationModel model)
        {
            if (!ModelState.IsValid)
            {
                return View(model);
            }
            var education = _mapper.Map<Education>(model);
            education.Created = DateTime.Now;
            education.Updated = DateTime.Now;
            await _educationRepository.AddAsync(education);
            _notyf.Success("Eğitim Eklendi...");
            return RedirectToAction("Index");
        }
        public async Task<IActionResult> Update(int id)
        {
            var lessons = await _lessonRepository.GetAllAsync();
            var lessonsSelectList = lessons.Select(x => new SelectListItem()
            {
                Text = x.Name,
                Value = x.Id.ToString()
            });
            ViewBag.Lessons = lessonsSelectList;
            var education = await _educationRepository.GetByIdAsync(id);
            var educationModel = _mapper.Map<EducationModel>(education);
            return View(educationModel);
        }

        [HttpPost]
        public async Task<IActionResult> Update(EducationModel model)
        {
            if (!ModelState.IsValid)
            {
                return View(model);
            }
            var education = await _educationRepository.GetByIdAsync(model.Id);
            education.Name = model.Name;
            education.Description = model.Description;
            education.IsActive = model.IsActive;
            education.LessonId = model.LessonId;
            education.Updated = DateTime.Now;

            await _educationRepository.UpdateAsync(education);
            _notyf.Success("Eğitim Güncellendi...");
            return RedirectToAction("Index");
        }
        public async Task<IActionResult> Delete(int id)
        {
            var education = await _educationRepository.GetByIdAsync(id);
            var educationModel = _mapper.Map<EducationModel>(education);
            return View(educationModel);
        }

        [HttpPost]
        public async Task<IActionResult> Delete(EducationModel model)
        {

            await _educationRepository.DeleteAsync(model.Id);
            _notyf.Success("Eğitim Silindi...");
            return RedirectToAction("Index");
        }
    }
}

EgitimPortali/Views/Education/Add.cshtml
@{
    Layout = "_LayoutAdmin";
}

@model EducationModel
@section CardHeader {
    <span>Eğitim Ekle</span>
}
<div class="row">
    <div class="col-md-4">
        @if (User.IsInRole("Admin") || User.IsInRole("Teacher"))
        {
            <form asp-controller="Education" asp-action="Add" method="post">

            <div class="mb-2">
                <label asp-for="Name"></label>
                <input asp-for="Name" class="form-control" />
                <span class="text-danger" asp-validation-for="Name"></span>
            </div>
            <div class="mb-2">
                <label asp-for="LessonId"> </label>
                <select asp-for="LessonId" class="form-control" asp-items="@ViewBag.Lessons">
                    <option value="">Seçiniz</option>
                </select>
            </div>
            <div class="mb-2">
                <label asp-for="Description"></label>
                <textarea asp-for="Description" class="form-control" rows="3"></textarea>
                <span class="text-danger" asp-validation-for="Description"></span>
            </div>
            <div class="mb-2">

                <input asp-for="IsActive" class="form-check-input" />
                <label asp-for="IsActive"></label>
                <span class="text-danger" asp-validation-for="IsActive"></span>
            </div>
            <div class="mb-2">
                <input type="submit" value="Kaydet" class="btn btn-primary btn-sm" />
            </div>
        </form>
        }
    </div>
</div>

@section Scripts {
    <partial name="_ValidationScriptsPartial" />
}

EgitimPortali/Views/Education/Delete.cshtml
@{
    Layout = "_LayoutAdmin";
}

@model EducationModel
@section CardHeader{
    <span>Eğitim Sil</span>
}
<h4>@Model.Name adlı eğitim silinecektir, Onaylıyor musunuz?</h4>

<form method="post" asp-action="Delete">
    <input type="hidden" asp-for="Id" />
    <input type="submit" value="Sil" class="btn btn-danger btn-sm" />
    <a asp-action="Index" class="btn btn-primary btn-sm">Vazgeç</a>
</form>

EgitimPortali/Views/Education/Index.cshtml
@{
    Layout = "_LayoutAdmin";
}

@model List<EducationModel>
@section CardHeader {
    <span>Eğitimler</span>
}
<a asp-action="Add" asp-controller="Education" class="btn btn-primary btn-sm mb-2">Ekle</a>

@if (Model.Count == 0)
{
    <div class="alert alert-danger col-md-4 mb-2">Henüz Eğitim Eklenmedi!</div>
}
<table class="table">
    <thead>
        <tr>
            <td>Id</td>
            <td>Eğitim Adı</td>
            <td>Durumu</td>
            <td>İşlemler</td>
        </tr>
    </thead>
    <tbody>
        @foreach (var education in Model)
        {
            <tr>
                <td>@education.Id</td>
                <td>@education.Name</td>
                <td>
                    @if (education.IsActive)
                    {
                        <span class="badge bg-success text-white">Aktif</span>
                    }
                    else
                    {
                        <span class="badge bg-danger text-white">Pasif</span>
                    }


                </td>
                <td>
                    @if (User.IsInRole("Admin")){
                    <a asp-action="Update" asp-controller="Education" class="btn btn-primary btn-sm" asp-route-id="@education.Id">Düzenle</a>
                    <a asp-action="Delete" asp-controller="Education" class="btn btn-danger btn-sm" asp-route-id="@education.Id">Sil</a>
                    }
                </td>
                <td>
                    @if (User.IsInRole("Teacher"))
                    {
                        <a asp-action="Update" asp-controller="Education" class="btn btn-primary btn-sm" asp-route-id="@education.Id">Düzenle</a>
                        <a asp-action="Delete" asp-controller="Education" class="btn btn-danger btn-sm" asp-route-id="@education.Id">Sil</a>
                    }
                </td>
                <td>
                    @if (User.IsInRole("Student"))
                    {
                        <a asp-action="Index" asp-controller="Home" class="btn btn-primary btn-sm" asp-route-id="@education.Id">İncele</a>
                        <a asp-action="Index" asp-controller="Home" class="btn btn-primary btn-sm" asp-route-id="@education.Id">Ders Videosu</a>

                    }
                </td>
            </tr>
        }
    </tbody>
</table>

EgitimPortali/Views/Education/Update.cshtml
@{
    Layout = "_LayoutAdmin";
}

@model EducationModel
@section CardHeader {
    <span>Eğitim Düzenle</span>
}
<div class="row">
    <div class="col-md-4">
        <form asp-controller="Education" asp-action="Update" method="post">

            <div class="mb-2">
                <label asp-for="Name"></label>
                <input asp-for="Name" class="form-control" />
                <span class="text-danger" asp-validation-for="Name"></span>
            </div>
            <div class="mb-2">
                <label asp-for="LessonId"> </label>
                <select asp-for="LessonId" class="form-control" asp-items="@ViewBag.Lessons">
                    <option value="">Seçiniz</option>
                </select>
            </div>
            <div class="mb-2">
                <label asp-for="Description"></label>
                <textarea asp-for="Description" class="form-control" rows="3"></textarea>
                <span class="text-danger" asp-validation-for="Description"></span>
            </div>
            <div class="mb-2">

                <input asp-for="IsActive" class="form-check-input" />
                <label asp-for="IsActive"></label>
                <span class="text-danger" asp-validation-for="IsActive"></span>
            </div>
            <div class="mb-2">
                <input type="submit" value="Kaydet" class="btn btn-primary btn-sm" />
            </div>
        </form>
    </div>
</div>

@section Scripts {
    <partial name="_ValidationScriptsPartial" />
}