EgitimPortali/Models/Lesson.cs
namespace EgitimPortali.Models
{
    public class Lesson : BaseEntity
    {
        public string Name { get; set; }
    }
}

EgitimPortali/Controllers/LessonController.cs
using AutoMapper;
using EgitimPortali.Models;
using AspNetCoreHero.ToastNotification.Abstractions;
using EgitimPortali.Repositories;
using EgitimPortali.ViewModels;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Authorization;

namespace EgitimPortali.Controllers
{
    public class LessonController : Controller
    {
        private readonly LessonRepository _lessonRepository;
        private readonly EducationRepository _educationRepository;
        private readonly INotyfService _notyf;
        private readonly IMapper _mapper;

        public LessonController(LessonRepository lessonRepository, INotyfService notyf, EducationRepository educationRepository, IMapper mapper)
        {
            _lessonRepository = lessonRepository;
            _notyf = notyf;
            _educationRepository = educationRepository;
            _mapper = mapper;
        }

        public async Task<IActionResult> Index()
        {
            var lessons = await _lessonRepository.GetAllAsync();
            var lessonModels = _mapper.Map<List<LessonModel>>(lessons);
            return View(lessonModels);
        }

        [Authorize(Roles = "Admin,Teacher")]
        public IActionResult Add()
        {
            return View();
        }
        [HttpPost]
        public async Task<IActionResult> Add(LessonModel model)
        {
            if (!ModelState.IsValid)
            {
                return View(model);
            }
            var lesson = _mapper.Map<Lesson>(model);
            lesson.Created = DateTime.Now;
            lesson.Updated = DateTime.Now;
            await _lessonRepository.AddAsync(lesson);
            _notyf.Success("Ders Eklendi...");
            return RedirectToAction("Index");
        }
        [Authorize(Roles = "Admin,Teacher")]
        public async Task<IActionResult> Update(int id)
        {
            var lesson = await _lessonRepository.GetByIdAsync(id);
            var lessonModel = _mapper.Map<LessonModel>(lesson);
            return View(lessonModel);
        }
        [HttpPost]
        public async Task<IActionResult> Update(LessonModel model)
        {
            if (!ModelState.IsValid)
            {
                return View(model);
            }
            var lesson = await _lessonRepository.GetByIdAsync(model.Id);
            lesson.Name = model.Name;
            lesson.IsActive = model.IsActive;
            lesson.Updated = DateTime.Now;
            await _lessonRepository.UpdateAsync(lesson);
            _notyf.Success("Ders Güncellendi...");
            return RedirectToAction("Index");
        }

        [Authorize(Roles = "Admin,Teacher")]
        public async Task<IActionResult> Delete(int id)
        {
            var lesson = await _lessonRepository.GetByIdAsync(id);
            var lessonModel = _mapper.Map<LessonModel>(lesson);
            return View(lessonModel);
        }
        [HttpPost]
        public async Task<IActionResult> Delete(LessonModel model)
        {
            var educations = await _educationRepository.GetAllAsync();
            if (educations.Count(c => c.LessonId == model.Id) > 0)
            {
                _notyf.Error("Eğitim Kayıtlı Olan Ders Silinemez!");
                return RedirectToAction("Index");
            }
            await _lessonRepository.DeleteAsync(model.Id);
            _notyf.Success("Ders Silindi...");
            return RedirectToAction("Index");
        }

    }
}

EgitimPortali/Views/Lesson/Add.cshtml
@{
    Layout = "_LayoutAdmin";
}

@model LessonModel
@section CardHeader {
    <span>Ders Ekle</span>
}
<div class="row">
    <div class="col-md-4">
        @if (User.IsInRole("Admin") || User.IsInRole("Teacher"))
        {
            <form asp-controller="Lesson" asp-action="Add" method="post">
                <div class="mb-2">
                <label asp-for="Name"></label>
                <input asp-for="Name" class="form-control" />
                <span class="text-danger" asp-validation-for="Name"></span>
            </div>
            <div class="mb-2">
                <input asp-for="IsActive" class="form-check-input" />
                <label asp-for="IsActive"></label>
                <span class="text-danger" asp-validation-for="IsActive"></span>
            </div>
            <div class="mb-2">
                <input type="submit" value="Kaydet" class="btn btn-primary btn-sm" />
            </div>
        </form>
        }
    </div>
</div>
@section Scripts {
    <partial name="_ValidationScriptsPartial" />
}

EgitimPortali/Views/Lesson/Delete.cshtml
@{
    Layout = "_LayoutAdmin";
}

@section CardHeader {
    <span>Ders Sil</span>
}
@model LessonModel
<h4>@Model.Name adlı ders silinecektir, Onaylıyor musunuz?</h4>
<form method="post" asp-action="Delete">
    <input type="hidden" asp-for="Id" />
    <input type="submit" value="Sil" class="btn btn-danger btn-sm" />
    <a asp-action="Index" class="btn btn-primary btn-sm">Vazgeç</a>
</form>

EgitimPortali/Views/Lesson/Index.cshtml
@{
    Layout = "_LayoutAdmin";
}

@model List<LessonModel>
@section CardHeader {
    <span>Dersler</span>
}
<a asp-action="Add" asp-controller="Lesson" class="btn btn-primary btn-sm mb-2">Ekle</a>
<table class="table">
    <thead>
        <tr>
            <th>Id</th>
            <th>Ders Adı</th>
            <th>Durumu</th>
            @if (User.IsInRole("Admin") || User.IsInRole("Teacher"))
        {
            <th>Düzenle - Sil</th>
        }
        </tr>
    </thead>
    <tbody>
        @foreach (var item in Model)
        {
            <tr>
                <td>@item.Id</td>
                <td>@item.Name</td>
                <td>
                    @if (item.IsActive)
                    {
                        <span class="badge bg-success text-white">Aktif</span>
                    }
                    else
                    {
                        <span class="badge bg-danger text-white">Pasif</span>
                    }
                </td>
                <td>
                    <a asp-action="Update" asp-route-id="@item.Id" class="btn btn-primary btn-sm">Düzenle</a>
                    <a asp-action="Delete" asp-route-id="@item.Id" class="btn btn-danger btn-sm">Sil</a>
                </td>
            </tr>
        }
    </tbody>
</table>

EgitimPortali/Views/Lesson/Update.cshtml
@{
    Layout = "_LayoutAdmin";
}

@model LessonModel
@section CardHeader {
    <span>Dersi Düzenle</span>
}
<div class="row">
    <div class="col-md-4">
        <form asp-controller="Lesson" asp-action="Update" method="post">
            <div class="mb-2">
                <label asp-for="Name"></label>
                <input asp-for="Id" class="form-control" type="hidden" />
                <input asp-for="Name" class="form-control" />
                <span class="text-danger" asp-validation-for="Name"></span>
            </div>
            <div class="mb-2">
                <input asp-for="IsActive" class="form-check-input" />
                <label asp-for="IsActive"></label>
                <span class="text-danger" asp-validation-for="IsActive"></span>
            </div>
            <div class="mb-2">
                <input type="submit" value="Kaydet" class="btn btn-primary btn-sm" />
            </div>
        </form>
    </div>
</div>
@section Scripts {
    <partial name="_ValidationScriptsPartial" />
}